spring:
  datasource:
    # For production, override with real database url/credentials:
    url: jdbc:postgresql://<DB_HOST>:5432/<DB_NAME>
    username: <DB_USER>
    password: <DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50

logging:
  level:
    root: INFO
    com.example.orderprocessing: INFO

# production scheduler rate (example: 5 minutes)
orders:
  processor:
    fixedRateMillis: 300000
